---
- hosts: webservers
  become: yes
  tasks:
    - apt:
        name: apache2
        state: present
        update_cache: yes
    - service:
        name: apache2
        state: started
        enabled: yes
